name: build

on:
  [ workflow_dispatch, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    
    - name: Build, test and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: gradle clean build sonarqube
      
    - name: Archive Jacoco code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-code-coverage-report
        path: build/reports/jacoco/test/html/
    
    - name: Publish to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        verbose: true
      
    - name: Publish to DockerHub
      run: gradle jib
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}

    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
